### ISSUE TITLE
the reconstruction shape in the VAE

### ISSUE THREAD

**Issue by zst91** [doublechenching/brats_segmentation-pytorch#4]
Thank you very much for your sharing your code. I am wondering whether the reconstruction shape in the forward function of VAE is correct.

The corresponding code is shown as following:
`self.reconstraction = nn.Sequential(nn.Linear(self.squeeze_channels // 2, init_channels * 8 * recon_shape),
                                            nn.ReLU(inplace=True))` in the init_ function, and
 `re_x = self.reconstraction(z)`
` recon_shape = [batch_size,
                       self.squeeze_channels // 2,
                       self.input_shape[0] // 16,
                       self.input_shape[1] // 16,
                       self.input_shape[2] // 16]`
`re_x = re_x.view(recon_shape)` in the forward function.
In my opinion, `recon_shape[1]` should be init_channels * 8. Am I right? Looking forward for your answer.

**Comment by QiushiYang** [comment]
I also met the mismatch error when running original codes. I found the code in line-93, unet.py maybe wrong, after replacing it with "self.squeeze_channels // 2 * 4", it could run and got the results.

**Comment by zst91** [comment]
Thanks for your answer. Yes, the recon_shape should be  "[batch_size, self.squeeze_channels // 2*4, self.input_shape[0] // 16, self.input_shape[1] // 16, self.input_shape[2] // 16]"
